### ISSUE TITLE
Where is the manifest.json?

### ISSUE THREAD

**Issue by Jlundmark12** [lumoslabs/zendesk_ticket_merger#2]
Can you please advise further installation instruction? I am receiving an error when trying to run zat package. The error message is "validate  Could not find manifest.json"

My understanding is every zendesk app requires a manifest.json file. 

Thanks!

**Comment by camertron** [comment]
Thanks @Jlundmark12, we're on it! https://github.com/lumoslabs/zendesk_ticket_merger/pull/3

**Comment by PolRod** [comment]
@Jlundmark12 we updated it with the manifest and an en.yml. `zat package` should work for you now!

**Comment by Jlundmark12** [comment]
Thank you! It works amazingly! Well done!
